### ISSUE TITLE
Missing step in usage guide?

### ISSUE THREAD

**Issue by EnMod** [ntdb/anchor-tags#1]
Following your usage guide in the readme to the T produces no visible results. I have a Tags field in posts and pages now, but going to the posts page and appending the ?tag= to the URL using some tags I just added does nothing.  Am I missing a step? Was one left out?

**Comment by ntdb** [comment]
Hey @EnMod, which version of Anchor are you using?

**Comment by EnMod** [comment]
I'm using 0.9.2, specifically nblackburn's bugfix/feature fork.  Nothing was dramatically changed in that fork such that this functionality shouldn't work, at least from what I gather.  [Here](https://github.com/nblackburn/anchor-cms) is said fork.

**Comment by ntdb** [comment]
Sorry about that, I've just submitted some bug fixes that should get everything up and running for you. I've tested it on @nblackburn's fork and everything looks good.
